using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace TrueCodeTestTask.DatabaseMigration.Migrations
{
    /// <inheritdoc />
    public partial class ChangeUserIdToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Currencies",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Currencies",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Currencies",
                keyColumn: "Id",
                keyValue: 3);

            // Step 1: Clear all UserCurrencies data since we're changing ID types
            migrationBuilder.Sql("DELETE FROM \"UserCurrencies\";");

            // Step 2: Drop foreign key constraint
            migrationBuilder.DropForeignKey(
                name: "FK_UserCurrencies_Users_UserId",
                table: "UserCurrencies");

            // Step 3: Drop the identity constraint and change the Users.Id column type
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY;");
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" TYPE uuid USING gen_random_uuid();");

            // Step 4: Set default value for new records
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" SET DEFAULT gen_random_uuid();");

            // Step 5: Change the UserCurrencies.UserId column type using raw SQL
            migrationBuilder.Sql("ALTER TABLE \"UserCurrencies\" ALTER COLUMN \"UserId\" TYPE uuid USING gen_random_uuid();");

            // Step 6: Recreate the foreign key constraint
            migrationBuilder.AddForeignKey(
                name: "FK_UserCurrencies_Users_UserId",
                table: "UserCurrencies",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Step 1: Drop foreign key constraint
            migrationBuilder.DropForeignKey(
                name: "FK_UserCurrencies_Users_UserId",
                table: "UserCurrencies");

            // Step 2: Change UserCurrencies.UserId back to integer using raw SQL
            migrationBuilder.Sql("ALTER TABLE \"UserCurrencies\" ALTER COLUMN \"UserId\" TYPE integer USING 1;");

            // Step 3: Remove the default UUID generation and change back to integer
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" TYPE integer USING 1;");
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            // Step 4: Recreate the foreign key constraint
            migrationBuilder.AddForeignKey(
                name: "FK_UserCurrencies_Users_UserId",
                table: "UserCurrencies",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
